default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rkbart
  password: password123
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: journal_app_development

test:
  <<: *default
  database: journal_app_test

production:
  primary: &primary_production
    <<: *default
    database: journal_app_production
    username: journal_app
    password: <%= ENV["JOURNAL_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: journal_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: journal_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: journal_app_production_cable
    migrations_paths: db/cable_migrate
